version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /tools/EVA.SDK.Generator.V2/validation/openapi
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /tools/EVA.SDK.Generator.V2/validation/swift
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
