version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /tools/EVA.SDK.Generator.V2/validation/openapi
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /tools/EVA.SDK.Generator.V2/validation/swift
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: nuget
    directory: /sdks/dotnet
    schedule:
      interval: weekly
    groups:
      dependencies:
          patterns:
              - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: nuget
    directory: /tools/EVA.API.Spec
    schedule:
      interval: weekly
    groups:
      dependencies:
          patterns:
              - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: nuget
    directory: /tools/EVA.SDK.Generator.V2
    schedule:
      interval: weekly
    groups:
      dependencies:
          patterns:
              - '*'
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /tools/EVA.SDK.Generator.V2/validation/openapi
    schedule:
      interval: weekly
    groups:
      dependencies:
          patterns:
              - '*'
    cooldown:
      default-days: 7
